travis:
  secure:
    BINSTAR_TOKEN: UDxTvp8p9rhj9ByujCGtxcFjCfT+39Xv7zzPE1iCk6RvLpv9xdgP4Xoh6Y8V+hoO2JbdtE11BZAkPPtALhqggpoqVDMHsTA1d7g5mK9ptT7RrWQtOn/ql22K9cNduAZwMJfTZ8sOGMxLlD0kMIh6RZ/rJofqN+B6O4wyDOLrVyaC9TWnwI/XN9gj0xbT+SBXQ45HGzNE2tiBg0BX+tVPPldJWS3CT0BG9o5ZNWqsahZppXk0W9XjAXASsPgVpIC5w55lWsp/S1qJ3JFEv7ztWukgyAwJ9CtRh+YDHAjY0Z8WPScIKqPeo2B5spE/MB4FVKbV/aDkcAXBzPgBPsDmmr5QXSCf7O81rGEZTZJMwIHH7Q1GuVHRUi6Tir978g2CxW9G47+WWmG5lwOGwuvQPZaFIBoE5Dy/8UqmuGqGhz0j+ThgAWy8OYVk2nSBiDlzw5IT4DiXDZldHSVohZKqDv64GmLaY+58GBlpRrYKtUlsMVrldYU8RZScM4aEaWr52JFryAwgr2mQUKtbFm92rmzGntTZ19VATrgjTyvZ9kTAtZvyzU8gGBde0vdqil9tHGzDEdadMDlaqEg/U8dT+KdNlDJFi21VPp+skpTTQ+3XkAyUShLW7CGB5mDeS1r3DRPjMLLJlVMUHwCn6Lf9l5gfr3mnP3DdjVu+RIlUQao=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
