travis:
  secure:
    BINSTAR_TOKEN: YJcCqIcWUov+F+nj2xzkQlbYrYSxm6wd8ri33vWwD4vfJWZXLpYqDpH95CBaySEThOeEqisozmO60Q3hnQfGp6br+ZxanHgJ0WsHOG1BOoq9d1v4Ty7UPZ9EK7MwS5HZGMoNNBQesIOHLSfZnN6BUi7f541EdE9eKR4N6iVhwCp/mlAWkVP7/vkYTJduOBSRbvqiGZoJ4CNJWDlk8WXFe3PIzFM40z4LiRA1nPQFnAJuLYu/QNX46D4QeyloIK/LA/jjHTA+9f56DtyGpxfNpPhBE7TkVsmCbhQEEDg18DyODRdm8Cfl995ljI0RVpSBaa1WgeZTHjRvVGRDfkLIlZbK5kyWC4jPcl6/g/SRzBNvFg5zVc3/EnJ6rXjXRndtD7C+weUAETbgmfk3ZhFnX8VRoM3ma0ZXBuwXEAvT0jnKSSVIiYbb0N8lO92NvnNPgwoMBFBL+vPb/SWfF+z3nKijnWlP1IDRcBstz68yZEIO9OHvGSDXRC+xovtvqv0rPUvXStLLBUMQkj1PL7DFMiB/100Io/i1duzezdepogT5mr7yGu2zrNg8T93y06ZReJRfHTmL1G7l2jc4T6kfy8jF25Q+Mu5z00/TEH/mWs1CLnUSx6dqL1ja3i0mhoB4e3F2z0P2517EV/6POP1cglhXBFayMawK6mEEqv2Q0Ak=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
